# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TrustlyTestObjC' do
  pod 'Cordova', '~> 3.9.1'
end
