
clean:
	rm -rf TrustlyTest/framework

TrustlyTest/framework:
	curl -LOk https://github.com/apache/cordova-android/archive/master.zip
	unzip master.zip
	mv cordova-android-master/framework TrustlyTest/
	rm -rf cordova-android-master master.zip
